/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";
import CategoryToggle from "./CategoryToggle";
import FeaturedProducts from "./FeaturedProducts";
import PopularCategories from "./PopularCategories";

const LuxuryShopPage = () => {
  return (
    <div className="flex flex-col justify-center bg-white">
      <div className="flex flex-col items-center px-5 pb-5 w-full bg-stone-50 max-md:max-w-full">
        <Header />
        <main>
          <HeroSection />
          <CategoryToggle />
          <FeaturedProducts />
          <PopularCategories />
        </main>
      </div>
    </div>
  );
};

export default LuxuryShopPage;
